# Generated by Django 5.2.17 on 2026-09-28 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase / Restock'), ('SALE', 'Customer Sale'), ('RETURN', 'Customer Return'), ('ADJUSTMENT', 'Manual Adjustment'), ('RESERVATION', 'Stock Reservation'), ('RELEASE', 'Reservation Release')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for addition, negative for deduction.')),
                ('reference', models.CharField(blank=True, help_text='e.g. Order ID or Restock Batch #', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
